### ISSUE TITLE
R Studio is now v2021.09.1

### ISSUE THREAD

**Issue by Tony-xy-Liu** [EDUCE-UBC/EDUCE-UBC.github.io#6]
The latest R studio version is now v2021.09.1-372
[R studio download page](https://www.rstudio.com/products/rstudio/download/#download)

please update [the install instructions](https://educe-ubc.github.io/r_and_rstudio.html)

**Comment by stephan-koenig** [comment]
Addressed with https://github.com/EDUCE-UBC/EDUCE-UBC.github.io/commit/99df72d4a3d0262c2541b0ed65e6baf2c9fbdc69
